from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Countdown(object):
    def setupUi(self, Countdown):
        Countdown.setObjectName("Countdown")
        Countdown.resize(488, 250)
        Countdown.setMinimumSize(QtCore.QSize(488, 250))
        Countdown.setStyleSheet("background-color: rgb(40, 41, 35);")
        self.centralwidget = QtWidgets.QWidget(Countdown)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(46)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(230, 200, 85);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.countdown = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.countdown.setFont(font)
        self.countdown.setStyleSheet("color: rgb(230, 200, 85);")
        self.countdown.setAlignment(QtCore.Qt.AlignCenter)
        self.countdown.setObjectName("countdown")
        self.gridLayout.addWidget(self.countdown, 1, 0, 1, 1)
        self.Close = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Close.setFont(font)
        self.Close.setStyleSheet("background-color: rgb(213, 0, 0);")
        self.Close.setAutoDefault(False)
        self.Close.setDefault(False)
        self.Close.setObjectName("Close")
        self.gridLayout.addWidget(self.Close, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(230, 200, 85);")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        Countdown.setCentralWidget(self.centralwidget)

        self.retranslateUi(Countdown)
        QtCore.QMetaObject.connectSlotsByName(Countdown)

    def retranslateUi(self, Countdown):
        _translate = QtCore.QCoreApplication.translate
        Countdown.setWindowTitle(_translate("Countdown", "Countdown"))
        self.label.setText(_translate("Countdown", "<html><head/><body><p align=\"center\">Please Wait</p></body></html>"))
        self.countdown.setText(_translate("Countdown", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><br/></p></body></html>"))
        self.Close.setText(_translate("Countdown", "Close"))
        self.label_3.setText(_translate("Countdown", "AIO \"GUI Edittion\" | Version: v-2.1.0 REV-2 | GUI Version:Alpha 0.0.1 | Copyright AIO 2022"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Countdown = QtWidgets.QCountdown()
    ui = Ui_Countdown()
    ui.setupUi(Countdown)
    Countdown.show()
    sys.exit(app.exec_())
